# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  taskmanagerapi:
    image: taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7283:7283
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
